name: 'do something in a docker'
description: 'Greet someone, record the time and say oi to the guv'
author: Yescaptain
branding:
  icon: 'anchor'
  color: 'blue'
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
  username:  # id of input
    description: 'username input'
    required: true
    default: 'World'
outputs:
  time: # id of output
    description: 'The time we greeted you'
  username: # id of output
    description: 'The user we got'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.who-to-greet }}