# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
#  for the call from caller.yml
  workflow_call:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - uses: Yescaptain/brodoo_actions/action.yml@main
      - name: Run a multi-line script
       id: same_step
      - with:
          username: "jurre"
          who-to-greet: "main man"
        run: |
          echo "The user was ${{ steps.same_step.outputs.username }}"
          echo test, and deploy your project.


