name: Call a reusable workflow

on:
  workflow_call:
  pull_request:
    branches:
      - main

jobs:
#  call-workflow:
#    uses: octo-org/example-repo/.github/workflows/workflow-A.yml@v1

  call-workflow-passing-data:
    uses: Yescaptain/brodoo_actions/action.yml@main
    with:
      username: 'breeze'
      who-to-greet: 'breezy the Octocat'